### PR TITLE
Update and rename __resource.lua to fxmanifest.lua

### PR DESCRIPTION
**Pull request by FBFezz**

### CODE REVIEW

**Comment by VenomXNL** [comment]
Doubting and not sure because i'm not playing anymore, but won't this invalidate it for non one-sync servers? or will this be usable for both server types?

**Comment by FBFezz** [comment]
No, its a fivem thing not onesync. __resource.lua is depreciated and fxmanifest is more updated. Can still use it for onesync and non onesync

**Comment by VenomXNL** [comment]
Thanks for confirming man :) I didn't develop nor played FiveM for a loooooong time by now :) will merge the request :) thanks for keeping it up-to-date :)

**Comment by VenomXNL** [comment]
Just noticed @TheNickoos also made changed to the resources.lua, will ask him, so with this message:
Would you mind to update and confirm this request @TheNickoos ? :)

**Comment by TheNickoos** [comment]
Its not really an **obligation** to have a fxmanifest.
__resource.lua is fine.

Please modify your fxmanifest with the new value Iv added into the resource.lua ;)

**Comment by FBFezz** [comment]
Yeah its not an obligation but its more supported now but Ill have a look at the new resource.lua now

**Comment by FBFezz** [comment]
Updated to the new one

**Comment by TheNickoos** [comment]
Approved.

**Pull request closed without merging**
